# Generated by Django 5.2.7 on 2025-10-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_airport_alter_flights_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=30)),
                ('last', models.CharField(max_length=30)),
                ('flight', models.ManyToManyField(blank=True, related_name='passenger', to='flights.flights')),
            ],
        ),
    ]
